---
- name: "Nextcloud finalize: check if webroot already exists"
  ansible.builtin.stat:
    path: "{{ nextcloud_instance }}"
  register: __nextcloud_instance_stat

- name: "Nextcloud finalize: optionally move away old webroot"
  ansible.builtin.command: "mv {{ nextcloud_instance }} {{ nextcloud_instance }}.{{ ansible_date_time.epoch }}"
  args:
    creates: "{{ nextcloud_instance }}.{{ ansible_date_time.epoch }}"
  when: __nextcloud_instance_stat.stat.exists

- name: "Nextcloud finalize: create webroot for new instance"
  ansible.builtin.file:
    path: "{{ nextcloud_instance }}"
    state: directory
    mode: 0755
  register: __nextcloud_instance_created

- name: "Nextcloud finalize: move new Nextcloud to nextcloud_instance"
  ansible.builtin.command: "cp -a {{ nextcloud_dl_tmp_dir }}/nextcloud/. {{ nextcloud_instance }}/"
  changed_when: True

- name: "Nextcloud finalize: remove temporary download directory"
  ansible.builtin.file:
    path: "{{ nextcloud_dl_tmp_dir }}"
    state: absent
  diff: False

- name: "Nextcloud finalize: change symlink to nextcloud_instance"
  ansible.builtin.file:
    src: "{{ nextcloud_instance.rsplit('/', 1)[-1] }}"
    dest: "{{ nextcloud_symlink }}"
    state: link
    owner: root
    group: root
