---
- name: "Nextcloud upgrade: set maintenance mode via occ commandline"
  become: True
  become_user: "{{ nextcloud_http_user }}"
  ansible.builtin.command: php occ maintenance:mode --on
  args:
    chdir: "{{ nextcloud_webroot_old }}"
  changed_when: True

- name: "Nextcloud upgrade: copy config.php over from old instance"
  ansible.builtin.copy:
    src: "{{ nextcloud_webroot_old }}/config/config.php"
    dest: "{{ nextcloud_dl_tmp_dir }}/nextcloud/config/config.php"
    remote_src: yes
    owner: "{{ nextcloud_http_user }}"
    group: "{{ nextcloud_http_group }}"
    mode: 0640

- name: "Nextcloud upgrade: run apps tasks"
  ansible.builtin.include_tasks: nextcloud/apps.yml
  vars:
    nextcloud_path: "{{ nextcloud_dl_tmp_dir }}/nextcloud"

- name: "Nextcloud upgrade: upgrade via occ commandline"
  become: True
  become_user: "{{ nextcloud_http_user }}"
  ansible.builtin.command: >
    php occ upgrade
    --no-interaction
    --no-warnings
  args:
    chdir: "{{ nextcloud_dl_tmp_dir }}/nextcloud"
  notify: Test and restart apache2
  changed_when: True

- name: "Nextcloud upgrade: run occ db:{{ item }}"
  become: True
  become_user: "{{ nextcloud_http_user }}"
  ansible.builtin.command: >
    php occ db:{{ item }}
  args:
    chdir: "{{ nextcloud_dl_tmp_dir }}/nextcloud"
  loop:
    - add-missing-columns
    - add-missing-indices
    - add-missing-primary-keys
  changed_when: True

- name: "Nextcloud upgrade: unset maintenance mode via occ commandline"
  become: True
  become_user: "{{ nextcloud_http_user }}"
  ansible.builtin.command: php occ maintenance:mode --off
  args:
    chdir: "{{ nextcloud_dl_tmp_dir }}/nextcloud"
  changed_when: True
